# Generated by Django 5.2 on 2026-01-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('birthdate', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'register',
                'managed': False,
            },
        ),
    ]
