# Generated by Django 5.2 on 2026-01-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PixelAuraplus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('username', models.CharField(max_length=45)),
                ('caption', models.TextField()),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
    ]
